######################################################################
# Automatically generated by qmake (3.0) ? 9? 1 19:29:11 2018
######################################################################

QT+=widgets svg xml
TEMPLATE = app
TARGET = src
INCLUDEPATH += .

# Input
HEADERS += dashboard_panel.hpp dashboard_panel_define.h
SOURCES += dashboard_panel.cpp main.cpp
